const defaultLinks = [
  {
    name: 'Office Slacking 4',
    url: 'http://www.supercoloring.com/sites/default/files/styles/coloring_full/public/cif/2017/03/cupcake-petal-shopkin-coloring-page.png',
    image: 'https://img.dogames.net/Office-Slacking-4.gif',
    description: 'Office Slacking 4',
    tags: ['ads', 'game'],
  },
  {
    name: 'Cute Unicorn Care',
    url: 'https://play.famobi.com/cute-unicorn-care',
    image: 'images/CuteUnicornCareTeaser.jpg',
    description: 'Cute Unicorn Care',
    tags: ['ads', 'html5', 'game'],
  },
  {
    name: 'Coloring Pages for Kids',
    url: 'https://picti.co/chrome/',
    image: 'images/picti.co_lion-new-min.png',
    description: 'Coloring Pages for Kids',
    tags: ['app', 'html5'],
  },
  {
    name: "PBS Kids' Games",
    url: 'http://pbskids.org/games/#topics-panel',
    image: 'https://www-tc.pbskids.org/shell/images/content/pbs-kids-logo.svg',
    description: 'PBS Kids Games',
    tags: ['collection', 'html5', 'game'],
  },
  {
    name: 'HTML5 Games / html5games.com',
    url: 'https://html5games.com/Girls/018103c4-e4a9-4b0e-86c1-5cc6782053ca',
    image: 'images/html5games_logo-min.png',
    description: 'HTML5 games / Girls',
    tags: ['collection', 'game', 'html5'],
  },
  {
    name: 'HTML5 Games / Poki.com',
    url: 'https://poki.com/en/html5',
    image: 'images/logo-poki.svg',
    description: 'Poki Games / HTML5',
    tags: ['game', 'collection', 'html5'],
  },
  {
    name: 'DoGames.Net / Kids',
    url: 'http://www.dogames.net/onlinegames/kids/?do',
    image: 'images/DoGames.Net.jpg',
    description: 'DoGames.Net',
    tags: ['game', 'collection', 'flash'],
  },
  {
    name: 'So Much Games / Baby Hazel',
    url: 'http://somuchgames.com/Category/hazel',
    image: 'images/SoMuchGames.com.jpg',
    description: 'So Much Games / Baby Hazel',
    tags: ['collection', 'game', 'flash'],
  },
  {
    name: 'Hero Games / Baby Hazel',
    url: 'http://www.iherogames.com/onlinegames/baby-hazel/',
    image: 'images/iHeroGames.com.jpg',
    description: 'Hero Games / Baby Hazel',
    tags: ['collection', 'game', 'flash'],
  },
  {
    name: 'Make Up Games / Dress Up Games',
    url: 'http://www.makeupgames.info/onlinegames/dress-up/?make',
    image: 'images/MakeUpGames.info.jpg',
    description: 'Make Up Games / Dress Up Games',
    tags: ['collection', 'game', 'flash'],
  },
  {
    name: 'Too Mad / Dress Up Games',
    url: 'http://www.toomad.com/onlinegames/dress-up/?t',
    image: 'images/TooMad.com.jpg',
    description: 'Too Mad / Dress Up Games',
    tags: ['collection', 'game', 'flash'],
  },
];
